# Generated by Django 4.0.4 on 2022-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_clientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
