# Generated by Django 4.0.4 on 2022-05-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_ordersno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersno',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Base.products', verbose_name='Product name'),
        ),
    ]
