# Generated by Django 4.0.4 on 2022-05-23 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_ordersno_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersno',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.products', verbose_name='Product name'),
        ),
    ]
